version: "3.9"
services:
  postgres_db:
      image: postgres
      environment:
        POSTGRES_USER: app
        POSTGRES_PASSWORD: apppassword
        POSTGRES_DB: test
      ports:
        - 5432:5432
      volumes:
        - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql